"""
Dual rendering paths for the Renderer agent.

Path A — HTML → PPTX (html2pptx.js via Node.js)
  Best for: editorial/professional styles (precise typography, grid systems)
  Input: HTML file generated by the Writer agent
  Output: a per-slide PPTX file produced by pptxgenjs

Path B — Image → PPTX (Gemini image generation + python-pptx)
  Best for: illustrated/artistic styles (Snoopy, Neo-Pop, etc.)
  Input: base_style_prompt + slide content description
  Output: a PNG image placed fullscreen on a slide

render_slide() chooses the path based on:
  1. slide_data['render_path'] override (if set)
  2. style_config['render_paths'][0] (first supported path)
  3. Global RENDER_PATH_DEFAULT setting ("auto" → Path A)
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import tempfile
import uuid
from pathlib import Path
from typing import Optional

from config import settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Scripts location (relative to project root, where the server runs from)
_SCRIPTS_DIR = Path(settings.SKILL_SCRIPTS_DIR)
_HTML2PPTX_RUNNER = _SCRIPTS_DIR / "html2pptx_runner.js"

# Temporary output directory for intermediate files
_TMP_DIR = Path(__file__).parent.parent.parent / "output" / "tmp"
_TMP_DIR.mkdir(parents=True, exist_ok=True)

# Timeouts (seconds)
_HTML_CONVERT_TIMEOUT = 120
_IMAGE_GEN_TIMEOUT = 90


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------

class SlideRenderResult:
    """Holds the result of rendering a single slide."""

    __slots__ = ("slide_index", "render_path", "output_path", "error", "placeholders")

    def __init__(
        self,
        slide_index: int,
        render_path: str,
        output_path: Optional[str] = None,
        error: Optional[str] = None,
        placeholders: Optional[list] = None,
    ) -> None:
        self.slide_index = slide_index
        self.render_path = render_path
        self.output_path = output_path
        self.error = error
        self.placeholders = placeholders or []

    @property
    def success(self) -> bool:
        return self.output_path is not None and self.error is None

    def to_dict(self) -> dict:
        return {
            "slide_index": self.slide_index,
            "render_path": self.render_path,
            "output_path": self.output_path,
            "error": self.error,
            "placeholders": self.placeholders,
            "success": self.success,
        }


# ---------------------------------------------------------------------------
# Path selection
# ---------------------------------------------------------------------------

def _choose_render_path(slide_data: dict, style_config: dict) -> str:
    """
    Return "path_a" or "path_b" for this slide.

    Priority:
      1. slide_data['render_path'] explicit override
      2. First entry in style_config['render_paths']
      3. RENDER_PATH_DEFAULT setting (default "auto" → path_a)
    """
    override = slide_data.get("render_path")
    if override in ("path_a", "path_b"):
        return override

    style_paths = style_config.get("render_paths", [])
    if style_paths:
        return style_paths[0]

    default = settings.RENDER_PATH_DEFAULT
    if default in ("path_a", "path_b"):
        return default

    return "path_a"  # safe fallback


# ---------------------------------------------------------------------------
# Path A — HTML → PPTX
# ---------------------------------------------------------------------------

def render_path_a(
    slide_data: dict,
    style_config: dict,
    slide_index: int,
) -> SlideRenderResult:
    """
    Convert an HTML slide file to a per-slide PPTX using html2pptx_runner.js.

    Expects slide_data to contain 'html_content' (str) or 'html_file' (str path).
    If 'html_content' is provided, a temporary file is written first.

    Returns SlideRenderResult with output_path pointing to a .pptx file.
    """
    run_id = uuid.uuid4().hex[:8]
    tmp_pptx = _TMP_DIR / f"slide_a_{slide_index}_{run_id}.pptx"

    # Resolve HTML source
    html_file = _resolve_html_file(slide_data, slide_index, run_id)
    if html_file is None:
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            error="No html_content or html_file in slide_data",
        )

    if not _HTML2PPTX_RUNNER.exists():
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            error=f"html2pptx_runner.js not found at {_HTML2PPTX_RUNNER}",
        )

    cmd = ["node", str(_HTML2PPTX_RUNNER), str(html_file), str(tmp_pptx)]
    logger.info("Path A: %s → %s", html_file.name, tmp_pptx.name)

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=_HTML_CONVERT_TIMEOUT,
        )

        if proc.returncode != 0:
            err = proc.stderr.strip() or proc.stdout.strip()
            logger.error("Path A failed (exit %d): %s", proc.returncode, err)
            return SlideRenderResult(
                slide_index=slide_index,
                render_path="path_a",
                error=f"html2pptx failed: {err[:500]}",
            )

        # Parse JSON result from runner
        try:
            result_json = json.loads(proc.stdout.strip())
        except json.JSONDecodeError:
            result_json = {}

        if not result_json.get("success"):
            error_msg = result_json.get("error", "Unknown error from html2pptx_runner")
            return SlideRenderResult(
                slide_index=slide_index,
                render_path="path_a",
                error=error_msg,
            )

        output_path = result_json.get("output_path", str(tmp_pptx))
        placeholders = result_json.get("placeholders", [])

        if not Path(output_path).exists():
            return SlideRenderResult(
                slide_index=slide_index,
                render_path="path_a",
                error="html2pptx runner reported success but output file not found",
            )

        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            output_path=output_path,
            placeholders=placeholders,
        )

    except subprocess.TimeoutExpired:
        logger.error("Path A timed out after %ds", _HTML_CONVERT_TIMEOUT)
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            error=f"html2pptx timed out after {_HTML_CONVERT_TIMEOUT}s",
        )
    except Exception as exc:
        logger.exception("Path A unexpected error")
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            error=str(exc),
        )
    finally:
        # Clean up temp HTML if we created it
        if html_file.name.startswith(f"slide_html_{slide_index}_{run_id}"):
            _safe_unlink(html_file)


def _resolve_html_file(slide_data: dict, slide_index: int, run_id: str) -> Optional[Path]:
    """Return a Path to an HTML file, writing a temp file if needed."""
    if "html_file" in slide_data:
        p = Path(slide_data["html_file"])
        return p if p.exists() else None

    html_content = slide_data.get("html_content", "")
    if not html_content:
        # Build minimal HTML from slide content as a last resort
        html_content = _build_minimal_html(slide_data)

    tmp_html = _TMP_DIR / f"slide_html_{slide_index}_{run_id}.html"
    tmp_html.write_text(html_content, encoding="utf-8")
    return tmp_html


def _build_minimal_html(slide_data: dict) -> str:
    """Generate a basic HTML slide from slide_data dict (fallback for Path A)."""
    title = slide_data.get("title", "")
    content = slide_data.get("content", {})
    bullet_points = content.get("bullet_points", [])

    bullets_html = "".join(f"<li>{bp}</li>" for bp in bullet_points)
    bullet_block = f"<ul>{bullets_html}</ul>" if bullet_points else ""

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{
    width: 1280px; height: 720px; margin: 0; padding: 0;
    font-family: 'Helvetica Neue', Arial, sans-serif;
    background: #FDFCF8;
    display: flex; flex-direction: column;
    justify-content: center; align-items: flex-start;
    box-sizing: border-box; padding: 80px;
  }}
  h1 {{ font-size: 48px; color: #2C2C24; margin: 0 0 40px 0; }}
  ul {{ font-size: 28px; color: #2C2C24; margin: 0; padding-left: 40px; }}
  li {{ margin-bottom: 16px; }}
</style>
</head>
<body>
  <h1>{title}</h1>
  {bullet_block}
</body>
</html>"""


# ---------------------------------------------------------------------------
# Path B — Image → PPTX
# ---------------------------------------------------------------------------

def render_path_b(
    slide_data: dict,
    style_config: dict,
    slide_index: int,
) -> SlideRenderResult:
    """
    Generate an AI illustration for the slide, then return the image path.

    The image will later be assembled into PPTX by pptx_assembler.
    Returns SlideRenderResult with output_path pointing to a .png file.
    """
    run_id = uuid.uuid4().hex[:8]
    output_png = _TMP_DIR / f"slide_b_{slide_index}_{run_id}.png"

    # Build the image prompt
    prompt = _build_image_prompt(slide_data, style_config)

    # Resolve style sample image (used as input reference)
    style_sample = _resolve_style_sample(style_config)

    # Get Gemini API key
    api_key = settings.GEMINI_API_KEY or os.environ.get("GEMINI_API_KEY", "")
    if not api_key:
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_b",
            error="GEMINI_API_KEY is not configured — cannot generate image",
        )

    script_path = _SCRIPTS_DIR / "generate_image.py"
    if not script_path.exists():
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_b",
            error=f"generate_image.py not found at {script_path}",
        )

    cmd = [
        "uv", "run", str(script_path),
        "--prompt", prompt,
        "--filename", str(output_png),
        "--resolution", "1K",
    ]
    if style_sample:
        cmd += ["--input-image", style_sample]

    env = {**os.environ, "GEMINI_API_KEY": api_key}
    logger.info("Path B: generating slide %d image → %s", slide_index, output_png.name)

    for attempt in range(2):
        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=_IMAGE_GEN_TIMEOUT,
                env=env,
            )

            if proc.returncode == 0 and output_png.exists():
                logger.info("Path B: slide %d image ready", slide_index)
                return SlideRenderResult(
                    slide_index=slide_index,
                    render_path="path_b",
                    output_path=str(output_png),
                )

            err = proc.stderr.strip()
            logger.warning(
                "Path B attempt %d/%d failed (exit %d): %s",
                attempt + 1, 2, proc.returncode, err[:200],
            )

        except subprocess.TimeoutExpired:
            logger.warning("Path B attempt %d/%d timed out", attempt + 1, 2)
            if attempt == 1:
                return SlideRenderResult(
                    slide_index=slide_index,
                    render_path="path_b",
                    error=f"Image generation timed out after {_IMAGE_GEN_TIMEOUT}s",
                )
        except Exception as exc:
            logger.exception("Path B unexpected error on attempt %d", attempt + 1)
            if attempt == 1:
                return SlideRenderResult(
                    slide_index=slide_index,
                    render_path="path_b",
                    error=str(exc),
                )

    return SlideRenderResult(
        slide_index=slide_index,
        render_path="path_b",
        error="Image generation failed after 2 attempts",
    )


def _build_image_prompt(slide_data: dict, style_config: dict) -> str:
    """Compose an image generation prompt from style + slide content."""
    base_prompt = style_config.get("base_style_prompt", "")

    title = slide_data.get("title", "")
    content = slide_data.get("content", {})
    bullet_points = content.get("bullet_points", [])

    # Build content description
    content_parts: list[str] = []
    if title:
        content_parts.append(f"SLIDE TITLE: {title}")
    if bullet_points:
        points_text = " | ".join(str(p) for p in bullet_points[:5])
        content_parts.append(f"KEY POINTS: {points_text}")

    content_description = " — ".join(content_parts)

    if base_prompt and content_description:
        return f"{base_prompt}\n\nCONTENT TO VISUALIZE: {content_description}"
    return base_prompt or content_description or "Professional presentation slide"


def _resolve_style_sample(style_config: dict) -> Optional[str]:
    """Return an absolute path to the style sample image, or None."""
    sample_url = style_config.get("sample_image_path", "")
    if not sample_url:
        return None

    # sample_image_path is "/static/styles/samples/style-XX.png"
    # Map to filesystem: backend/static/styles/samples/style-XX.png
    relative = sample_url.lstrip("/")
    candidate = Path(__file__).parent.parent.parent / relative
    return str(candidate) if candidate.exists() else None


# ---------------------------------------------------------------------------
# Unified dispatch with fallback chain
# ---------------------------------------------------------------------------

def render_slide(
    slide_data: dict,
    style_config: dict,
    slide_index: int,
) -> SlideRenderResult:
    """
    Route a single slide to Path A or Path B and return the result.

    Fallback chain (graceful degradation):
      Path B → Path A (if Path B fails)
      Path A → Basic python-pptx text-only (if html2pptx fails)

    Never mutates slide_data or style_config.
    """
    path = _choose_render_path(slide_data, style_config)
    logger.debug("Slide %d → %s", slide_index, path)

    if path == "path_a":
        result = render_path_a(slide_data, style_config, slide_index)
        if not result.success:
            logger.warning(
                "Path A failed for slide %d, falling back to python-pptx text slide: %s",
                slide_index, result.error,
            )
            return _render_fallback_text_slide(slide_data, slide_index, result.error)
        return result

    else:  # path_b
        result = render_path_b(slide_data, style_config, slide_index)
        if not result.success:
            logger.warning(
                "Path B failed for slide %d, falling back to Path A: %s",
                slide_index, result.error,
            )
            # Enrich slide_data with fallback note
            fallback_slide = {
                **slide_data,
                "render_path": "path_a",
                "_fallback_from": "path_b",
                "_fallback_reason": result.error,
            }
            fallback_result = render_path_a(fallback_slide, style_config, slide_index)
            if not fallback_result.success:
                logger.warning(
                    "Path A fallback also failed for slide %d, using text-only slide: %s",
                    slide_index, fallback_result.error,
                )
                return _render_fallback_text_slide(
                    slide_data, slide_index,
                    f"Path B: {result.error} | Path A: {fallback_result.error}",
                )
            # Mark as fallback in result metadata
            return SlideRenderResult(
                slide_index=slide_index,
                render_path="path_a_fallback",
                output_path=fallback_result.output_path,
                placeholders=fallback_result.placeholders,
            )
        return result


def _render_fallback_text_slide(
    slide_data: dict,
    slide_index: int,
    original_error: str = "",
) -> SlideRenderResult:
    """
    Last-resort fallback: create a basic python-pptx text-only slide.
    Returns a SlideRenderResult pointing to a temporary .pptx file.
    """
    import uuid
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    run_id = uuid.uuid4().hex[:8]
    out_path = _TMP_DIR / f"slide_fallback_{slide_index}_{run_id}.pptx"

    try:
        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        blank_layout = prs.slide_layouts[min(6, len(prs.slide_layouts) - 1)]
        slide = prs.slides.add_slide(blank_layout)

        # Light background
        bg = slide.background
        bg.fill.solid()
        bg.fill.fore_color.rgb = RGBColor(0xFD, 0xFC, 0xF8)

        title = slide_data.get("title", "")
        content = slide_data.get("content", {})
        bullet_points = content.get("bullet_points", [])

        # Title
        if title:
            txb = slide.shapes.add_textbox(
                Inches(0.5), Inches(0.5), Inches(12.3), Inches(1.5)
            )
            tf = txb.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.text = title
            p.font.size = Pt(40)
            p.font.bold = True
            p.font.color.rgb = RGBColor(0x2C, 0x2C, 0x24)

        # Bullet points
        if bullet_points:
            txb2 = slide.shapes.add_textbox(
                Inches(0.5), Inches(2.2), Inches(12.3), Inches(5.0)
            )
            tf2 = txb2.text_frame
            tf2.word_wrap = True
            for i, point in enumerate(bullet_points[:4]):
                if i == 0:
                    p2 = tf2.paragraphs[0]
                else:
                    p2 = tf2.add_paragraph()
                p2.text = f"• {point}"
                p2.font.size = Pt(24)
                p2.font.color.rgb = RGBColor(0x2C, 0x2C, 0x24)

        prs.save(str(out_path))
        logger.info("Fallback text slide created for slide %d", slide_index)

        return SlideRenderResult(
            slide_index=slide_index,
            render_path="fallback_text",
            output_path=str(out_path),
        )

    except Exception as exc:
        logger.exception("Fallback text slide creation failed for slide %d", slide_index)
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="fallback_text",
            error=f"All fallbacks failed. Original: {original_error[:200]}. Fallback: {exc}",
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_unlink(p: Path) -> None:
    try:
        p.unlink(missing_ok=True)
    except Exception:
        pass
