"""
Dual rendering paths for the Renderer agent.

Path A — HTML → PPTX (html2pptx.js via Node.js)
  Best for: editorial/professional styles (precise typography, grid systems)
  Input: HTML file generated by the Writer agent
  Output: a per-slide PPTX file produced by pptxgenjs

Path B — Image → PPTX (Gemini image generation + python-pptx)
  Best for: illustrated/artistic styles (Snoopy, Neo-Pop, etc.)
  Input: base_style_prompt + slide content description
  Output: a PNG image placed fullscreen on a slide

render_slide() chooses the path based on:
  1. slide_data['render_path'] override (if set)
  2. style_config['render_paths'][0] (first supported path)
  3. Global RENDER_PATH_DEFAULT setting ("auto" → Path A)
"""

from __future__ import annotations

import html
import json
import logging
import subprocess
import uuid
from pathlib import Path
from typing import Optional

from config import settings
from skills.runtime import get_skill_runtime_packet

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Scripts location (resolved from SkillRuntime first, settings second)
_SKILL_PACKET = get_skill_runtime_packet()
_SCRIPTS_DIR = Path(_SKILL_PACKET.get("scripts_dir") or settings.SKILL_SCRIPTS_DIR)
_HTML2PPTX_RUNNER = _SCRIPTS_DIR / "html2pptx_runner.js"

# Temporary output directory for intermediate files
_TMP_DIR = Path(__file__).parent.parent.parent / "output" / "tmp"
_TMP_DIR.mkdir(parents=True, exist_ok=True)

# Timeouts (seconds)
_HTML_CONVERT_TIMEOUT = 120


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------

class SlideRenderResult:
    """Holds the result of rendering a single slide."""

    __slots__ = ("slide_index", "render_path", "output_path", "error", "placeholders")

    def __init__(
        self,
        slide_index: int,
        render_path: str,
        output_path: Optional[str] = None,
        error: Optional[str] = None,
        placeholders: Optional[list] = None,
    ) -> None:
        self.slide_index = slide_index
        self.render_path = render_path
        self.output_path = output_path
        self.error = error
        self.placeholders = placeholders or []

    @property
    def success(self) -> bool:
        return self.output_path is not None and self.error is None

    def to_dict(self) -> dict:
        return {
            "slide_index": self.slide_index,
            "render_path": self.render_path,
            "output_path": self.output_path,
            "error": self.error,
            "placeholders": self.placeholders,
            "success": self.success,
        }


# ---------------------------------------------------------------------------
# Path selection
# ---------------------------------------------------------------------------

def _choose_render_path(slide_data: dict, style_config: dict) -> str:
    """
    Return "path_a" or "path_b" for this slide.

    Priority:
      1. slide_data['render_path'] explicit override
      2. First entry in style_config['render_paths']
      3. RENDER_PATH_DEFAULT setting (default "auto" → path_a)
    """
    override = slide_data.get("render_path")
    if override in ("path_a", "path_b"):
        return override

    style_paths = style_config.get("render_paths", [])
    if style_paths:
        return style_paths[0]

    default = settings.RENDER_PATH_DEFAULT
    if default in ("path_a", "path_b"):
        return default

    return "path_a"  # safe fallback


# ---------------------------------------------------------------------------
# Path A — HTML → PPTX
# ---------------------------------------------------------------------------

def render_path_a(
    slide_data: dict,
    style_config: dict,
    slide_index: int,
) -> SlideRenderResult:
    """
    Convert an HTML slide file to a per-slide PPTX using html2pptx_runner.js.

    Expects slide_data to contain 'html_content' (str) or 'html_file' (str path).
    If 'html_content' is provided, a temporary file is written first.

    Returns SlideRenderResult with output_path pointing to a .pptx file.
    """
    run_id = uuid.uuid4().hex[:8]
    tmp_pptx = _TMP_DIR / f"slide_a_{slide_index}_{run_id}.pptx"

    # Resolve HTML source
    html_file = _resolve_html_file(slide_data, slide_index, run_id)
    if html_file is None:
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            error="No html_content or html_file in slide_data",
        )

    if not _HTML2PPTX_RUNNER.exists():
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            error=f"html2pptx_runner.js not found at {_HTML2PPTX_RUNNER}",
        )

    cmd = ["node", str(_HTML2PPTX_RUNNER), str(html_file), str(tmp_pptx)]
    logger.info("Path A: %s → %s", html_file.name, tmp_pptx.name)

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=_HTML_CONVERT_TIMEOUT,
        )

        if proc.returncode != 0:
            err = proc.stderr.strip() or proc.stdout.strip()
            logger.error("Path A failed (exit %d): %s", proc.returncode, err)
            return SlideRenderResult(
                slide_index=slide_index,
                render_path="path_a",
                error=f"html2pptx failed: {err[:500]}",
            )

        # Parse JSON result from runner
        try:
            result_json = json.loads(proc.stdout.strip())
        except json.JSONDecodeError:
            result_json = {}

        if not result_json.get("success"):
            error_msg = result_json.get("error", "Unknown error from html2pptx_runner")
            return SlideRenderResult(
                slide_index=slide_index,
                render_path="path_a",
                error=error_msg,
            )

        output_path = result_json.get("output_path", str(tmp_pptx))
        placeholders = result_json.get("placeholders", [])

        if not Path(output_path).exists():
            return SlideRenderResult(
                slide_index=slide_index,
                render_path="path_a",
                error="html2pptx runner reported success but output file not found",
            )

        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            output_path=output_path,
            placeholders=placeholders,
        )

    except subprocess.TimeoutExpired:
        logger.error("Path A timed out after %ds", _HTML_CONVERT_TIMEOUT)
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            error=f"html2pptx timed out after {_HTML_CONVERT_TIMEOUT}s",
        )
    except Exception as exc:
        logger.exception("Path A unexpected error")
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_a",
            error=str(exc),
        )
    finally:
        # Clean up temp HTML if we created it
        if html_file.name.startswith(f"slide_html_{slide_index}_{run_id}"):
            _safe_unlink(html_file)


def _resolve_html_file(slide_data: dict, slide_index: int, run_id: str) -> Optional[Path]:
    """Return a Path to an HTML file, writing a temp file if needed."""
    if "html_file" in slide_data:
        p = Path(slide_data["html_file"])
        return p if p.exists() else None

    html_content = slide_data.get("html_content", "")
    if not html_content:
        # Build minimal HTML from slide content as a last resort
        html_content = _build_minimal_html(slide_data)

    tmp_html = _TMP_DIR / f"slide_html_{slide_index}_{run_id}.html"
    tmp_html.write_text(html_content, encoding="utf-8")
    return tmp_html


def _build_minimal_html(slide_data: dict) -> str:
    """Generate a basic HTML slide from slide_data dict (fallback for Path A)."""
    title = slide_data.get("title", "")
    content = slide_data.get("content", {})
    bullet_points = content.get("bullet_points", [])
    speaker_notes = slide_data.get("speaker_notes", "")

    # Use color_system if available
    colors = slide_data.get("color_system", {})
    bg_color = colors.get("background", "#FDFCF8")
    text_color = colors.get("text", "#2C2C24")
    accent_color = colors.get("accent", "#5D7052")

    safe_title = html.escape(title)
    bullets_html = "".join(f"<li>{html.escape(str(bp))}</li>" for bp in bullet_points)
    bullet_block = f"<ul>{bullets_html}</ul>" if bullet_points else ""

    # Add notes as a hidden data attribute for reference
    notes_attr = f' data-notes="{html.escape(speaker_notes[:200])}"' if speaker_notes else ""

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{
    width: 1280px; height: 720px; margin: 0; padding: 0;
    font-family: 'Helvetica Neue', Arial, 'PingFang SC', 'Microsoft YaHei', sans-serif;
    background: {bg_color};
    display: flex; flex-direction: column;
    justify-content: center; align-items: flex-start;
    box-sizing: border-box; padding: 80px;
  }}
  h1 {{ font-size: 44px; color: {text_color}; margin: 0 0 40px 0; line-height: 1.3; }}
  ul {{ font-size: 26px; color: {text_color}; margin: 0; padding-left: 40px; }}
  li {{ margin-bottom: 16px; line-height: 1.5; }}
  li::marker {{ color: {accent_color}; }}
</style>
</head>
<body{notes_attr}>
  <h1>{safe_title}</h1>
  {bullet_block}
</body>
</html>"""


# ---------------------------------------------------------------------------
# Path B — Image → PPTX
# ---------------------------------------------------------------------------

def render_path_b(
    slide_data: dict,
    style_config: dict,
    slide_index: int,
) -> SlideRenderResult:
    """
    Generate an AI illustration for the slide, then return the image path.

    Uses google-genai SDK directly (via script_wrappers/image_gen.py) with
    the 12ai proxy configured in settings.

    Returns SlideRenderResult with output_path pointing to a .png file.
    """
    run_id = uuid.uuid4().hex[:8]
    output_png = _TMP_DIR / f"slide_b_{slide_index}_{run_id}.png"

    # Build the image prompt
    prompt = _build_image_prompt(slide_data, style_config)

    # Resolve style sample image (used as input reference)
    style_sample = _resolve_style_sample(style_config)

    # Check API key
    api_key = settings.IMAGEN_API_KEY or settings.GEMINI_API_KEY
    if not api_key:
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="path_b",
            error="IMAGEN_API_KEY is not configured — cannot generate image",
        )

    logger.info("Path B: generating slide %d image → %s", slide_index, output_png.name)

    from services.script_wrappers.image_gen import generate_image

    for attempt in range(2):
        try:
            result_path = generate_image(
                prompt=prompt,
                output_path=str(output_png),
                input_image=style_sample,
                api_key=api_key,
                base_url=settings.IMAGEN_BASE_URL,
                model=settings.IMAGEN_MODEL,
                image_size=settings.IMAGEN_IMAGE_SIZE,
                number_of_images=settings.IMAGEN_NUMBER_OF_IMAGES,
            )

            if result_path and output_png.exists():
                logger.info("Path B: slide %d image ready", slide_index)
                return SlideRenderResult(
                    slide_index=slide_index,
                    render_path="path_b",
                    output_path=result_path,
                )

            logger.warning(
                "Path B attempt %d/%d returned no image",
                attempt + 1, 2,
            )

        except ValueError as exc:
            logger.warning("Path B validation error: %s", exc)
            return SlideRenderResult(
                slide_index=slide_index,
                render_path="path_b",
                error=str(exc),
            )
        except Exception as exc:
            logger.warning(
                "Path B attempt %d/%d failed: %s", attempt + 1, 2, exc
            )
            if attempt == 1:
                return SlideRenderResult(
                    slide_index=slide_index,
                    render_path="path_b",
                    error=str(exc),
                )

    return SlideRenderResult(
        slide_index=slide_index,
        render_path="path_b",
        error="Image generation failed after 2 attempts",
    )


def _build_image_prompt(slide_data: dict, style_config: dict) -> str:
    """
    Compose an image generation prompt from style + slide content.

    Priority:
      1) Writer/Visual crafted `image_prompt`
      2) style `base_style_prompt`
      3) fallback title/bullets summary
    """
    base_prompt = (style_config.get("base_style_prompt") or "").strip()
    draft_prompt = (slide_data.get("image_prompt") or "").strip()

    title = (slide_data.get("title") or "").strip()
    content = slide_data.get("content", {}) or {}
    text_to_render = slide_data.get("text_to_render", {}) or {}

    render_title = (text_to_render.get("title") or title).strip()
    render_subtitle = (text_to_render.get("subtitle") or "").strip()
    render_bullets = text_to_render.get("bullets") or content.get("bullet_points", [])
    if not isinstance(render_bullets, list):
        render_bullets = []

    sections: list[str] = []
    if base_prompt:
        sections.append(base_prompt)
    if draft_prompt:
        sections.append(f"DESIGN INTENT:\n{draft_prompt}")

    text_lines: list[str] = []
    if render_title:
        text_lines.append(f'- Title: "{render_title}"')
    if render_subtitle:
        text_lines.append(f'- Subtitle: "{render_subtitle}"')
    for bullet in render_bullets[:4]:
        text_lines.append(f'- Bullet: "{str(bullet)}"')
    if text_lines:
        sections.append(
            "TEXT TO RENDER (keep exact wording and clear legibility):\n"
            + "\n".join(text_lines)
        )

    fallback_content: list[str] = []
    if title:
        fallback_content.append(f"SLIDE TITLE: {title}")
    if content.get("bullet_points"):
        points_text = " | ".join(str(p) for p in content.get("bullet_points", [])[:5])
        fallback_content.append(f"KEY POINTS: {points_text}")
    if fallback_content:
        sections.append("CONTENT CONTEXT:\n" + " — ".join(fallback_content))

    if not sections:
        return "Professional presentation slide, strong visual metaphor, 16:9 composition."
    return "\n\n".join(sections)


def _resolve_style_sample(style_config: dict) -> Optional[str]:
    """Return an absolute path to the style sample image, or None."""
    sample_url = style_config.get("sample_image_path", "")
    style_id = str(style_config.get("id") or style_config.get("style_id") or "").strip()
    backend_root = Path(__file__).parent.parent.parent
    project_root = backend_root.parent

    candidates: list[Path] = []

    if not sample_url:
        sample_name = ""
    else:
        sample_name = Path(sample_url).name
        # sample_image_path is "/static/styles/samples/style-XX.png"
        # Map to filesystem: backend/static/styles/samples/style-XX.png
        relative = sample_url.lstrip("/")
        candidates.append(backend_root / relative)

    # Fallback to SkillRuntime style sample dir so huashu-slides assets can be reused.
    style_samples_dir_raw = Path(_SKILL_PACKET.get("style_samples_dir") or settings.STYLE_SAMPLES_DIR)
    style_sample_dirs: list[Path]
    if style_samples_dir_raw.is_absolute():
        style_sample_dirs = [style_samples_dir_raw]
    else:
        style_sample_dirs = [
            style_samples_dir_raw,
            backend_root / style_samples_dir_raw,
            project_root / style_samples_dir_raw,
        ]

    existing_dirs = [d for d in style_sample_dirs if d.exists()]
    for style_samples_dir in existing_dirs:
        names: list[str] = []
        if sample_name:
            names.append(sample_name)
        if style_id:
            names.extend([
                f"style-{style_id}.png",
                f"{style_id}.png",
            ])
        # Keep order stable while de-duplicating.
        unique_names = list(dict.fromkeys(names))
        for name in unique_names:
            candidates.append(style_samples_dir / name)

    for path in candidates:
        if path.exists():
            return str(path.resolve())
    return None


# ---------------------------------------------------------------------------
# Unified dispatch with fallback chain
# ---------------------------------------------------------------------------

def render_slide(
    slide_data: dict,
    style_config: dict,
    slide_index: int,
) -> SlideRenderResult:
    """
    Route a single slide to Path A or Path B and return the result.

    Fallback chain (graceful degradation):
      Path B → Path A (if Path B fails)
      Path A → Basic python-pptx text-only (if html2pptx fails)

    Never mutates slide_data or style_config.
    """
    path = _choose_render_path(slide_data, style_config)
    logger.debug("Slide %d → %s", slide_index, path)

    if path == "path_a":
        result = render_path_a(slide_data, style_config, slide_index)
        if not result.success:
            logger.warning(
                "Path A failed for slide %d, falling back to python-pptx text slide: %s",
                slide_index, result.error,
            )
            return _render_fallback_text_slide(slide_data, slide_index, result.error)
        return result

    else:  # path_b
        result = render_path_b(slide_data, style_config, slide_index)
        if not result.success:
            logger.warning(
                "Path B failed for slide %d, falling back to Path A: %s",
                slide_index, result.error,
            )
            # Enrich slide_data with fallback note
            fallback_slide = {
                **slide_data,
                "render_path": "path_a",
                "_fallback_from": "path_b",
                "_fallback_reason": result.error,
            }
            fallback_result = render_path_a(fallback_slide, style_config, slide_index)
            if not fallback_result.success:
                logger.warning(
                    "Path A fallback also failed for slide %d, using text-only slide: %s",
                    slide_index, fallback_result.error,
                )
                return _render_fallback_text_slide(
                    slide_data, slide_index,
                    f"Path B: {result.error} | Path A: {fallback_result.error}",
                )
            # Mark as fallback in result metadata
            return SlideRenderResult(
                slide_index=slide_index,
                render_path="path_a_fallback",
                output_path=fallback_result.output_path,
                placeholders=fallback_result.placeholders,
            )
        return result


def _render_fallback_text_slide(
    slide_data: dict,
    slide_index: int,
    original_error: str = "",
) -> SlideRenderResult:
    """
    Last-resort fallback: create a basic python-pptx text-only slide.
    Returns a SlideRenderResult pointing to a temporary .pptx file.
    """
    import uuid
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    run_id = uuid.uuid4().hex[:8]
    out_path = _TMP_DIR / f"slide_fallback_{slide_index}_{run_id}.pptx"

    try:
        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        blank_layout = prs.slide_layouts[min(6, len(prs.slide_layouts) - 1)]
        slide = prs.slides.add_slide(blank_layout)

        # Light background
        bg = slide.background
        bg.fill.solid()
        bg.fill.fore_color.rgb = RGBColor(0xFD, 0xFC, 0xF8)

        title = slide_data.get("title", "")
        content = slide_data.get("content", {})
        bullet_points = content.get("bullet_points", [])

        # Title
        if title:
            txb = slide.shapes.add_textbox(
                Inches(0.5), Inches(0.5), Inches(12.3), Inches(1.5)
            )
            tf = txb.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.text = title
            p.font.size = Pt(40)
            p.font.bold = True
            p.font.color.rgb = RGBColor(0x2C, 0x2C, 0x24)

        # Bullet points
        if bullet_points:
            txb2 = slide.shapes.add_textbox(
                Inches(0.5), Inches(2.2), Inches(12.3), Inches(5.0)
            )
            tf2 = txb2.text_frame
            tf2.word_wrap = True
            for i, point in enumerate(bullet_points[:4]):
                if i == 0:
                    p2 = tf2.paragraphs[0]
                else:
                    p2 = tf2.add_paragraph()
                p2.text = f"• {point}"
                p2.font.size = Pt(24)
                p2.font.color.rgb = RGBColor(0x2C, 0x2C, 0x24)

        prs.save(str(out_path))
        logger.info("Fallback text slide created for slide %d", slide_index)

        return SlideRenderResult(
            slide_index=slide_index,
            render_path="fallback_text",
            output_path=str(out_path),
        )

    except Exception as exc:
        logger.exception("Fallback text slide creation failed for slide %d", slide_index)
        return SlideRenderResult(
            slide_index=slide_index,
            render_path="fallback_text",
            error=f"All fallbacks failed. Original: {original_error[:200]}. Fallback: {exc}",
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_unlink(p: Path) -> None:
    try:
        p.unlink(missing_ok=True)
    except Exception:
        pass


def cleanup_tmp_files(max_age_hours: int = 6) -> int:
    """Remove temp files older than max_age_hours. Returns count removed."""
    import time
    cutoff = time.time() - max_age_hours * 3600
    removed = 0
    for f in _TMP_DIR.iterdir():
        if f.is_file() and f.stat().st_mtime < cutoff:
            f.unlink(missing_ok=True)
            removed += 1
    return removed
